language: node_js
node_js:
  - "8"
sudo: true
env:
  - CXX=clang-3.6 MONGODB_VERSION=3.2.9
compiler: clang-3.6
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8
