// Error commands
var ERRORS = {};
ERRORS.NO_SUCH_COMMAND = 0;
ERRORS.FIND_COMMAND_FAILURE = 1;
ERRORS.GENERAL_COMMAND_FAILURE = 2;
ERRORS.GETMORE_COMMAND_FAILURE = 3;
ERRORS.CURSOR_NOT_FOUND = 4;
ERRORS.REPLACE_CONTAINS_OPERATORS = 5;
ERRORS.LIVE_QUERY_ID_ILLEGAL = 6;
ERRORS.NO_LIVE_QUERY_CHANNEL_HANDLER = 7;
ERRORS.PRE_CONDITION_FAILED = 8;

module.exports = ERRORS;
